create schema user_schema;

set search_path to user_schema;

create table member
(
    id         uuid primary key   default gen_random_uuid(),
    seq_id     bigint    not null unique generated by default as identity (minvalue 1),
    username   text      not null unique,
    email      text      not null unique,
    first_name text,
    last_name  text      not null,
    age        smallint,
    phone      text      not null,
    address    text,
    role       smallint  not null default 1 check ( role in (0, 1, 2, 3, 4, 5)), -- 停、訪、般、商、高、頂
    created_at timestamp not null default now()
);

create table member_auths
(
    id          bigint primary key generated by default as identity (minvalue 1),
    member_id   uuid not null references member (id),
    provider    text not null,
    provider_id text,
    password    text,
    check (
        (provider = 'local' and password is not null) or
        (provider != 'local' and password is null)
        )
);

create table login_logs
(
    id         bigint primary key generated always as identity (minvalue 1),
    member_id  uuid      not null references member (id),
    provider   text      not null,
    attempt_at timestamp not null default now(),
    ip_address text,
    is_success bool      not null
);